# model
model_name_or_path: unsloth/llama-3-8b-bnb-4bit

# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

# dataset
dataset: huanhuan
template: llama3
cutoff_len: 1024
max_samples: 1000
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/llama3-8b/lora/sft-fun
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 0.00005
num_train_epochs: 8.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
